version: '3.5'

services:
  client:
    image: client
    build:
      context: ./webapp
      dockerfile: Dockerfile

  backend:
    image: server
    depends_on:
      db:
        condition: service_started
    build:
      context: ./server
      dockerfile: Dockerfile

  db:
    container_name: db
    image: postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgres/data
    restart: always
    env_file:
      - .env # The name of your environment file (the one at the repository root)
    environment:
      - POSTGRES_DB=db

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './docker/nginx/conf.d/default.conf:/etc/nginx/nginx.conf'
