version: '3.5'

services:
  client:
    image: client
    ports: 
      - "5001:3000"
    build:
      context: ./webapp
      dockerfile: Dockerfile

  backend:
    image: server
    depends_on:
      - db
    ports: 
      - "5000:8080"
    build:
      context: ./server
      dockerfile: Dockerfile

  db:
    container_name: db
    ports: 
      - "5433:5432"
    image: postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgres/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=db


  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './docker/nginx/conf.d/default.conf:/etc/nginx/nginx.conf'
